export const CANVAS_WIDTH = 800;
export const CANVAS_HEIGHT = 600;

export const GAME_CONSTANTS = {
  BALL_SIZE: 5,
  TARGET_SIZE: 20,
  CANNON_WIDTH: 40,
  CANNON_HEIGHT: 60,
  SHOOT_INTERVAL: 200,
  BALL_LIFETIME: 3000,
  PARTICLE_LIFETIME: 1000,
  RESPAWN_DELAY: 1000,
  MAX_ROTATION: Math.PI / 3,
  SHOOT_FORCE: 0.02,
  GRAVITY: 0.5,
} as const;